### PR TITLE
Allow additional tags to be passed to the module

### PR DESCRIPTION
**Pull request by MarkFGarner**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

***

Fixes #0000

***

Release note for [CHANGELOG](https://github.com/traveloka/terraform-aws-private-route53-zone/blob/master/CHANGELOG.md):

```release-note
NOTES:

* Any Notes regarding your submitted PR, like breaking changes or else.

FEATURES:

* **New Source:** `aws_000_0000` ([#references_to_issue](./))

ENHANCEMENTS:

* feature: Add support for new version of AWS API

BUG FIXES:

* Prevent error from evil bugs
```

***

Output from `terraform plan` command from changes you propose.

```
$ terraform plan

```

### CODE REVIEW

**Comment by MarkFGarner** [comment]
@didilmfs Sorry to bother you, is there anything I need to do to get a review on this?

**Comment by vincenttjia** [comment]
Hi @MarkFGarner, I am currently reviewing your changes. I will be pushing some additional changes to your branch to conform with our company naming standards, then I will be merging this. Thank you for your contribution.

**Review by vincenttjia — APPROVED** [review]
Thank you for your contribution

**Comment by vincenttjia** [comment]
Hi @MarkFGarner I wanted to merge this pull request but unfortunately, The base branch requires all commits to be signed.

Could you help me sign your commit, feel free to squash mine into them as well

First you would need to set this up

Official guide from github:
- https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
- https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
- https://docs.github.com/en/authentication/managing-commit-signature-verification/associating-an-email-with-your-gpg-key
- https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
Easier guide to follow IMO: https://codex.so/gpg-verification-github

Then after that you need to re-commit your changes

```
git checkout allow-custom-tags
```

```
git pull origin allow-custom-tags
```

```
git reset --soft 28e2ba4982c5d2194747bae60a4ef3de9db01366
```

```
git commit -S -m "YOUR_COMMIT_MESSAGE"
```

```
git push -f origin allow-custom-tags
```

Once you are done we should be able to merge your commit. Thank you

**Comment by MarkFGarner** [comment]
Hi @vincenttjia,

Wow! Thanks so much for that quick and detailed reply, super helpful.

Hopefully that should be sorted now but let me know if I need to do anything :)

**Review by vincenttjia — APPROVED** [review]

**Comment by vincenttjia** [comment]
Hi @MarkFGarner I believe that you still have not done this step https://docs.github.com/en/authentication/managing-commit-signature-verification/associating-an-email-with-your-gpg-key

image

Because the commit is still unverified with this error, it needs to show as verified on github. Thank you

**Comment by vincenttjia** [comment]
Yup found it

your commit email is mark.garner@ospreyfs.com
while your gpg email is markfgarner@gmail.com

You would need to make it the same to make your commit verified

**Comment by MarkFGarner** [comment]
Damn, silly mistake - I'll get that sorted soon as well. Thanks so much again for all your support.

**Comment by MarkFGarner** [comment]
Done, cannot thank you enough for the help!

Issue was starting this PR on my personal device and updating it on now on my work device

**Review by vincenttjia — APPROVED** [review]

**Comment by vincenttjia** [comment]
Merged, thank you @MarkFGarner for your contribution

I have released a new version as well https://github.com/traveloka/terraform-aws-private-route53-zone/releases/tag/v0.5.1

**Pull request merged**
